#!/usr/bin/env bash
# deploy.sh — blue/green swap (http) or tag-pointer swap (cli)
# Called by .git/hooks/post-merge (or manually via echelon.deploy)
set -euo pipefail

PROJECT_ROOT=$(git rev-parse --show-toplevel)

_resolve_squad_dir() {
  local base current_file run_id
  if [ -n "${ECHELON_SQUAD_DIR:-}" ]; then
    echo "${ECHELON_SQUAD_DIR}"
    return 0
  fi

  for base in runs; do
    current_file="${PROJECT_ROOT}/${base}/.current"
    if [ -f "${current_file}" ]; then
      run_id=$(tr -d '[:space:]' < "${current_file}")
      if [ -n "${run_id}" ] && [ -d "${PROJECT_ROOT}/${base}/${run_id}" ]; then
        echo "${PROJECT_ROOT}/${base}/${run_id}"
        return 0
      fi
    fi
  done

  echo "${PROJECT_ROOT}/runs"
}

SQUAD_DIR="$(_resolve_squad_dir)"
STATE_FILE="${ECHELON_DEPLOY_STATE_FILE:-${SQUAD_DIR}/deploy-state.json}"

if [ ! -f "${STATE_FILE}" ]; then
  echo "✗ deploy-state.json not found. Run echelon.run first to initialize deploy." >&2
  exit 1
fi

# ── CI/CD Freshness Check ─────────────────────────────────────────────────────
FINGERPRINT_SCRIPT="$(CDPATH='' cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/cicd-fingerprint.sh"
if [ -f "${FINGERPRINT_SCRIPT}" ]; then
  if ! bash "${FINGERPRINT_SCRIPT}" --check >/dev/null 2>&1; then
    echo "✗ CI/CD artifacts are stale or missing." >&2
    echo "  Project dependencies or Dockerfiles have changed since the last echelon.cicd run." >&2
    echo "  Run: speckit.echelon.deploy  (auto-regenerates CI/CD before deploying)" >&2
    exit 1
  fi
fi

# ── Read state ────────────────────────────────────────────────────────────────
_state=$(STATE_FILE="${STATE_FILE}" python3 - <<'PYEOF'
import os, sys, json
try:
    with open(os.environ['STATE_FILE']) as f:
        d = json.load(f)
    print(d.get('type', 'http'))
    print(d['app'])
    print(d['active'])
    print(d.get('blue_port') or '')
    print(d.get('green_port') or '')
    print(d.get('dockerfile', 'Dockerfile'))
    print(d.get('health_check', ''))
    print(d.get('install_path', ''))
    print(d.get('container_port', 80))
except Exception as e:
    sys.exit(f'Cannot read deploy state: {e}')
PYEOF
)
DEPLOY_TYPE=$(echo "${_state}"      | sed -n '1p')
APP=$(echo "${_state}"              | sed -n '2p')
ACTIVE=$(echo "${_state}"           | sed -n '3p')
BLUE_PORT=$(echo "${_state}"        | sed -n '4p')
GREEN_PORT=$(echo "${_state}"       | sed -n '5p')
DOCKERFILE=$(echo "${_state}"       | sed -n '6p')
HEALTH_CHECK=$(echo "${_state}"     | sed -n '7p')
INSTALL_PATH=$(echo "${_state}"     | sed -n '8p')
CONTAINER_PORT=$(echo "${_state}"   | sed -n '9p')
CONTAINER_PORT="${CONTAINER_PORT:-80}"

INACTIVE=$([ "${ACTIVE}" = "blue" ] && echo "green" || echo "blue")

# ── Derive helper paths ───────────────────────────────────────────────────────
# SCRIPTS_DIR: where this script lives (same dir as fix-spa-base.sh, etc.)
SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# APP_DIR: the directory containing the Dockerfile — for monorepos this is
# apps/web/ not the project root, and is where framework configs live.
APP_DIR="$(dirname "${PROJECT_ROOT}/${DOCKERFILE}")"

# ── Auto-generate Dockerfile if missing ───────────────────────────────────────
if [ ! -f "${PROJECT_ROOT}/${DOCKERFILE}" ]; then
  echo "deploy: ${DOCKERFILE} not found — auto-generating from project type..."
  _generated=false

  if [ -f "${PROJECT_ROOT}/package.json" ]; then
    if grep -qE '"vite"|"@vitejs' "${PROJECT_ROOT}/package.json" 2>/dev/null; then
      # Vite/React static site → nginx multi-stage
      cat > "${PROJECT_ROOT}/${DOCKERFILE}" << 'DEOF'
# Auto-generated by echelon deploy — Vite/React static site
FROM node:20-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
DEOF
      echo "deploy: generated Dockerfile (Vite/React → nginx)"
      _generated=true
    else
      # Generic Node app
      _start=$(python3 -c "import json; d=json.load(open('${PROJECT_ROOT}/package.json')); print(d.get('scripts',{}).get('start','node index.js'))" 2>/dev/null || echo "node index.js")
      cat > "${PROJECT_ROOT}/${DOCKERFILE}" << DEOF
# Auto-generated by echelon deploy — Node.js app
FROM node:20-slim
WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts
COPY . .
EXPOSE 3000
CMD ["sh", "-c", "${_start}"]
DEOF
      echo "deploy: generated Dockerfile (Node.js)"
      _generated=true
    fi
  elif [ -f "${PROJECT_ROOT}/pyproject.toml" ] || [ -f "${PROJECT_ROOT}/requirements.txt" ]; then
    _req=$([ -f "${PROJECT_ROOT}/pyproject.toml" ] && echo "pyproject.toml" || echo "requirements.txt")
    cat > "${PROJECT_ROOT}/${DOCKERFILE}" << DEOF
# Auto-generated by echelon deploy — Python app
FROM python:3.12-slim
WORKDIR /app
COPY ${_req} ./
RUN pip install --no-cache-dir $([ "${_req}" = "pyproject.toml" ] && echo "-e ." || echo "-r requirements.txt")
COPY . .
EXPOSE 8000
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
DEOF
    echo "deploy: generated Dockerfile (Python)"
    _generated=true
  elif [ -f "${PROJECT_ROOT}/go.mod" ]; then
    _module=$(head -1 "${PROJECT_ROOT}/go.mod" | awk '{print $2}')
    _bin=$(basename "${_module}")
    cat > "${PROJECT_ROOT}/${DOCKERFILE}" << DEOF
# Auto-generated by echelon deploy — Go app
FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /app/${_bin} .

FROM alpine:latest
COPY --from=build /app/${_bin} /usr/local/bin/${_bin}
EXPOSE 8080
CMD ["${_bin}"]
DEOF
    echo "deploy: generated Dockerfile (Go)"
    _generated=true
  fi

  if [ "${_generated}" = "false" ]; then
    echo "✗ Cannot auto-generate Dockerfile: unknown project type." >&2
    echo "  Create a ${DOCKERFILE} at the project root and re-run deploy." >&2
    exit 1
  fi

  echo "deploy: ⚠ Dockerfile auto-generated — review and commit it."
  echo "         git add ${DOCKERFILE} && git commit -m 'chore: add Dockerfile'"
fi

# ── Resolve env file for build args ──────────────────────────────────────────
# deploy.build_env_file in echelon-config.yml overrides root .env.local (useful for
# monorepos where the app's env lives in e.g. apps/web/.env.local).
ECHELON_YML="${PROJECT_ROOT}/echelon-config.yml"
_build_env_file=""
if [ -f "${ECHELON_YML}" ]; then
  _build_env_file=$(python3 -c "
import yaml, sys
try:
    c = yaml.safe_load(open('${ECHELON_YML}'))
    print(c.get('deploy', {}).get('build_env_file', ''))
except Exception: pass
" 2>/dev/null || true)
fi

_env_path=""
if [ -n "${_build_env_file}" ] && [ -f "${PROJECT_ROOT}/${_build_env_file}" ]; then
  _env_path="${PROJECT_ROOT}/${_build_env_file}"
elif [ -f "${PROJECT_ROOT}/.env.local" ]; then
  _env_path="${PROJECT_ROOT}/.env.local"
fi

# ── Load build args ───────────────────────────────────────────────────────────
BUILD_ARGS=()
if [ -n "${_env_path}" ]; then
  _arg_count=0
  while IFS='=' read -r _key _rest; do
    [[ -z "${_key}" || "${_key}" =~ ^[[:space:]]*# ]] && continue
    BUILD_ARGS+=(--build-arg "${_key}=${_rest}")
    _arg_count=$((_arg_count + 1))
  done < "${_env_path}"
  echo "deploy: injecting ${_arg_count} build arg(s) from ${_env_path}"
fi

# ── Load runtime env vars ─────────────────────────────────────────────────────
# Written to a temp env-file so values with spaces/newlines (e.g. PEM keys)
# are passed intact — unquoted string interpolation word-splits on spaces.
# Sources (in order, last line wins on conflict):
#   1. deploy.env block in echelon-config.yml — explicit key-value pairs
#   2. Non-NEXT_PUBLIC_* vars from the env file (secrets baked in at build time
#      via ARG are not in the image env — pass them again at runtime)
RUN_ENV_FILE="/tmp/echelon-run-env-${APP}.env"
: > "${RUN_ENV_FILE}"

if [ -f "${ECHELON_YML}" ]; then
  python3 -c "
import yaml, sys
try:
    c = yaml.safe_load(open('${ECHELON_YML}'))
    env = c.get('deploy', {}).get('env', {}) or {}
    for k, v in env.items():
        print(f'{k}={v}')
except Exception: pass
" 2>/dev/null >> "${RUN_ENV_FILE}" || true
fi

if [ -n "${_env_path}" ]; then
  while IFS='=' read -r _key _rest; do
    [[ -z "${_key}" || "${_key}" =~ ^[[:space:]]*# ]] && continue
    [[ "${_key}" =~ ^NEXT_PUBLIC_ ]] && continue  # baked into bundle at build time
    printf '%s=%s\n' "${_key}" "${_rest}" >> "${RUN_ENV_FILE}"
  done < "${_env_path}"
fi

if [ -s "${RUN_ENV_FILE}" ]; then
  _env_count=$(wc -l < "${RUN_ENV_FILE}" | tr -d '[:space:]')
  echo "deploy: injecting ${_env_count} runtime env var(s) via env-file"
fi

# ── Read health_check_path ────────────────────────────────────────────────────
# Optional path that must return 2xx to confirm the app bundle is healthy.
# Falls back to any-HTTP-response check when not set.
# Set in echelon-config.yml deploy.health_check_path (e.g. /api/health).
HEALTH_CHECK_PATH=""
if [ -f "${ECHELON_YML}" ]; then
  HEALTH_CHECK_PATH=$(python3 -c "
import yaml, sys
try:
    c = yaml.safe_load(open('${ECHELON_YML}'))
    print(c.get('deploy', {}).get('health_check_path', ''))
except Exception: pass
" 2>/dev/null || true)
fi

# ══════════════════════════════════════════════════════════════════════════════
# CLI PATH
# ══════════════════════════════════════════════════════════════════════════════
if [ "${DEPLOY_TYPE}" = "cli" ]; then
  echo "deploy: ${APP} (cli) ${ACTIVE} → ${INACTIVE}"

  # ── Build ─────────────────────────────────────────────────────────────────
  if [ -f "${SCRIPTS_DIR}/fix-spa-base.sh" ]; then
    bash "${SCRIPTS_DIR}/fix-spa-base.sh" "${PROJECT_ROOT}" "${APP}" "${APP_DIR}"
  fi
  echo "deploy: building ${APP}:candidate..."
  docker build -t "${APP}:candidate" "${BUILD_ARGS[@]}" -f "${PROJECT_ROOT}/${DOCKERFILE}" "${PROJECT_ROOT}"

  # ── Health check (optional) ───────────────────────────────────────────────
  # HEALTH_CHECK is intentionally unquoted so multi-word commands split correctly
  # (e.g. "myapp --version" becomes: docker run --rm myapp:candidate myapp --version)
  if [ -n "${HEALTH_CHECK}" ]; then
    echo "deploy: health check — docker run --rm ${APP}:candidate ${HEALTH_CHECK}"
    # shellcheck disable=SC2086
    if ! docker run --rm "${APP}:candidate" ${HEALTH_CHECK}; then
      echo "✗ Health check failed. Rolling back (build discarded)." >&2
      echo "  Active slot '${ACTIVE}' unchanged." >&2
      exit 1
    fi
    echo "deploy: health check passed"
  else
    echo "deploy: health check skipped (health_check not configured)"
  fi

  # ── Tag ───────────────────────────────────────────────────────────────────
  docker tag "${APP}:candidate" "${APP}:${INACTIVE}"
  echo "deploy: tagged ${APP}:candidate → ${APP}:${INACTIVE}"

  # ── Update state ──────────────────────────────────────────────────────────
  STATE_FILE="${STATE_FILE}" APP="${APP}" INACTIVE="${INACTIVE}" python3 - <<'PYEOF'
import os, sys, json, datetime

state_file = os.environ['STATE_FILE']
app = os.environ['APP']
inactive = os.environ['INACTIVE']

with open(state_file) as f:
    state = json.load(f)

state['active'] = inactive
state[f'{inactive}_image'] = f'{app}:{inactive}'
state['last_deploy'] = datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00', 'Z')

with open(state_file, 'w') as f:
    json.dump(state, f, indent=2)

global_dir = os.path.expanduser("~/.speckit-deploy")
os.makedirs(global_dir, exist_ok=True)
global_state = os.path.join(global_dir, f"{state['app']}.json")
with open(global_state, 'w') as f:
    json.dump(state, f, indent=2)
PYEOF

  echo ""
  echo "════════════════════════════════════════"
  echo "  ✓ ${APP} deployed (cli)"
  echo "  Slot:   ${INACTIVE} (was ${ACTIVE})"
  echo "  Image:  ${APP}:${INACTIVE}"
  if [ -n "${INSTALL_PATH}" ]; then
    EXPANDED=$(INSTALL_PATH="${INSTALL_PATH}" python3 -c "import os; print(os.path.expanduser(os.environ['INSTALL_PATH']))")
    echo "  Run:    ${EXPANDED}/${APP} [args...]"
  else
    echo "  Run:    docker run --rm ${APP}:${INACTIVE} [args...]"
  fi
  echo "════════════════════════════════════════"
  exit 0
fi

# ══════════════════════════════════════════════════════════════════════════════
# HTTP PATH — shared Traefik :80, PathPrefix(/{APP}) routing
# ══════════════════════════════════════════════════════════════════════════════
INACTIVE_PORT=$([ "${INACTIVE}" = "blue" ] && echo "${BLUE_PORT}" || echo "${GREEN_PORT}")

echo "deploy: ${APP} ${ACTIVE} → ${INACTIVE} (health-check port ${INACTIVE_PORT})"

# ── Traefik health ────────────────────────────────────────────────────────────
TRAEFIK_STATUS=$(docker inspect --format='{{.State.Status}}' speckit-traefik 2>/dev/null | tr -d '[:space:]' || true)
[ -z "${TRAEFIK_STATUS}" ] && TRAEFIK_STATUS="missing"
if [ "${TRAEFIK_STATUS}" != "running" ]; then
  echo "✗ speckit-traefik is not running (status: ${TRAEFIK_STATUS})." >&2
  echo "  Run: docker start speckit-traefik" >&2
  exit 1
fi

# ── Remove stale inactive container if present ────────────────────────────────
if docker inspect "${APP}-${INACTIVE}" >/dev/null 2>&1; then
  echo "deploy: removing stale ${APP}-${INACTIVE}..."
  docker rm -f "${APP}-${INACTIVE}" >/dev/null
fi

# ── SPA base-path correction (idempotent) ────────────────────────────────────
if [ -f "${SCRIPTS_DIR}/fix-spa-base.sh" ]; then
  bash "${SCRIPTS_DIR}/fix-spa-base.sh" "${PROJECT_ROOT}" "${APP}" "${APP_DIR}"
fi

# ── Build ─────────────────────────────────────────────────────────────────────
echo "deploy: building ${APP}:candidate..."
docker build -t "${APP}:candidate" "${BUILD_ARGS[@]}" -f "${PROJECT_ROOT}/${DOCKERFILE}" "${PROJECT_ROOT}"

# ── Start inactive slot ───────────────────────────────────────────────────────
# -p binds the health-check port to the host; Traefik routes via Docker network.
echo "deploy: starting ${APP}-${INACTIVE} (Traefik: http://localhost/${APP}/, health: :${INACTIVE_PORT})..."
docker run -d \
  --name "${APP}-${INACTIVE}" \
  --network speckit-deploy \
  --label "traefik.enable=true" \
  --label "traefik.http.routers.${APP}.rule=PathPrefix(\`/${APP}\`)" \
  --label "traefik.http.routers.${APP}.entrypoints=web" \
  --label "traefik.http.routers.${APP}.middlewares=${APP}-strip" \
  --label "traefik.http.middlewares.${APP}-strip.stripprefix.prefixes=/${APP}" \
  --label "traefik.http.services.${APP}.loadbalancer.server.port=${CONTAINER_PORT}" \
  -p "${INACTIVE_PORT}:${CONTAINER_PORT}" \
  --env-file "${RUN_ENV_FILE}" \
  "${APP}:candidate"

# ── Health check (via host-bound port) ───────────────────────────────────────
# Two modes:
#   health_check_path set → must return 2xx (verifies app logic works)
#   not set              → accepts any HTTP response (verifies server is up)
# Set deploy.health_check_path in echelon-config.yml for stricter checking, e.g.:
#   health_check_path: /api/health
if [ -n "${HEALTH_CHECK_PATH}" ]; then
  echo "deploy: health check on http://localhost:${INACTIVE_PORT}${HEALTH_CHECK_PATH} (strict: 2xx required)..."
else
  echo "deploy: health check on http://localhost:${INACTIVE_PORT} (permissive: any HTTP response)..."
fi
HEALTHY=0
for i in 1 2 3 4 5; do
  sleep 2
  if [ -n "${HEALTH_CHECK_PATH}" ]; then
    _code=$(curl -so /dev/null -w '%{http_code}' "http://localhost:${INACTIVE_PORT}${HEALTH_CHECK_PATH}" 2>/dev/null || true)
    if [[ "${_code}" =~ ^2 ]]; then
      HEALTHY=1
      echo "deploy: health check passed (attempt ${i}, HTTP ${_code})"
      break
    fi
    echo "deploy: attempt ${i}/5 — not yet healthy (HTTP ${_code:-000})..."
  else
    _code=$(curl -so /dev/null -w '%{http_code}' "http://localhost:${INACTIVE_PORT}" 2>/dev/null || true)
    if [ -n "${_code}" ] && [ "${_code}" != "000" ]; then
      HEALTHY=1
      echo "deploy: health check passed (attempt ${i}, HTTP ${_code})"
      break
    fi
    echo "deploy: attempt ${i}/5 — not yet healthy..."
  fi
done

if [ "${HEALTHY}" = "0" ]; then
  echo "✗ Health check failed after 5 attempts. Rolling back." >&2
  docker stop "${APP}-${INACTIVE}" 2>/dev/null || true
  docker rm "${APP}-${INACTIVE}" 2>/dev/null || true
  echo "  Active slot '${ACTIVE}' unchanged." >&2
  exit 1
fi

# ── Stop old slot ─────────────────────────────────────────────────────────────
echo "deploy: stopping ${APP}-${ACTIVE}..."
docker stop "${APP}-${ACTIVE}" 2>/dev/null || echo "  (${APP}-${ACTIVE} was not running)"

# ── Tag and update state ──────────────────────────────────────────────────────
docker tag "${APP}:candidate" "${APP}:${INACTIVE}"
echo "deploy: tagged ${APP}:candidate → ${APP}:${INACTIVE}"

STATE_FILE="${STATE_FILE}" APP="${APP}" INACTIVE="${INACTIVE}" python3 - <<'PYEOF'
import os, sys, json, datetime

state_file = os.environ['STATE_FILE']
app = os.environ['APP']
inactive = os.environ['INACTIVE']

with open(state_file) as f:
    state = json.load(f)

state['active'] = inactive
state[f'{inactive}_image'] = f'{app}:{inactive}'
state['last_deploy'] = datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00', 'Z')

with open(state_file, 'w') as f:
    json.dump(state, f, indent=2)

global_dir = os.path.expanduser("~/.speckit-deploy")
os.makedirs(global_dir, exist_ok=True)
global_state = os.path.join(global_dir, f"{state['app']}.json")
with open(global_state, 'w') as f:
    json.dump(state, f, indent=2)
PYEOF

echo ""
echo "════════════════════════════════════════"
echo "  ✓ ${APP} deployed"
echo "  Slot:   ${INACTIVE} (was ${ACTIVE})"
echo "  Live:   http://localhost/${APP}/"
echo "════════════════════════════════════════"
