/**
 * Belief Base — stores ground atoms with O(1) add/remove/query.
 * Belief changes generate events for the reasoning cycle.
 */

import { beliefKey, EventKind } from "./types.js";

export class BeliefBase {
  /** @type {Set<string>} Set of canonical belief keys for O(1) membership test */
  #keys = new Set();
  /** @type {Map<string, import('./types.js').Belief>} Map from key to Belief for retrieval */
  #beliefs = new Map();
  /** @type {import('./types.js').AgentEvent[]} Pending events generated by belief changes */
  #pendingEvents = [];

  /** Number of beliefs currently held */
  get size() {
    return this.#keys.size;
  }

  /** Read-only view of all belief keys (for plan context evaluation) */
  get keySet() {
    return this.#keys;
  }

  /** Add a belief. Returns true if it was new, false if already present. */
  add(b) {
    const key = beliefKey(b);
    if (this.#keys.has(key)) return false;
    this.#keys.add(key);
    this.#beliefs.set(key, b);
    this.#pendingEvents.push({
      kind: EventKind.BeliefAdd,
      functor: b.functor,
      args: b.args,
    });
    return true;
  }

  /** Remove a belief. Returns true if it existed. */
  remove(b) {
    const key = beliefKey(b);
    if (!this.#keys.has(key)) return false;
    this.#keys.delete(key);
    this.#beliefs.delete(key);
    this.#pendingEvents.push({
      kind: EventKind.BeliefDel,
      functor: b.functor,
      args: b.args,
    });
    return true;
  }

  /** Check if a belief is present (exact match). */
  has(b) {
    return this.#keys.has(beliefKey(b));
  }

  /** Check if a belief key string is present. */
  hasKey(key) {
    return this.#keys.has(key);
  }

  /** Query beliefs by functor. Returns all beliefs with the given functor. */
  query(functor) {
    const results = [];
    for (const b of this.#beliefs.values()) {
      if (b.functor === functor) results.push(b);
    }
    return results;
  }

  /** Number of pending belief-change events (non-destructive check). */
  get pendingEventCount() {
    return this.#pendingEvents.length;
  }

  /** Drain all pending events (belief add/del) since last drain. */
  drainEvents() {
    const events = [...this.#pendingEvents];
    this.#pendingEvents.length = 0;
    return events;
  }

  /** Get all beliefs as an array (for debugging/inspection). */
  all() {
    return [...this.#beliefs.values()];
  }

  /** Clear all beliefs and pending events. */
  clear() {
    this.#keys.clear();
    this.#beliefs.clear();
    this.#pendingEvents.length = 0;
  }
}
