"""Unit tests for deterministic spec artifact maps."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import pytest

from echelon.artifact_index import (
    infer_lifecycle_stage,
    render_artifact_index,
    write_artifact_index,
)


GENERATED_AT = datetime(2026, 6, 4, 12, 0, tzinfo=timezone.utc)


def _make_spec_dir(tmp_path: Path) -> Path:
    spec_dir = tmp_path / "specs" / "024-artifacts"
    spec_dir.mkdir(parents=True)
    return spec_dir


@pytest.mark.unit
def test_render_lists_present_known_artifacts(tmp_path: Path) -> None:
    spec_dir = _make_spec_dir(tmp_path)
    (spec_dir / "00-overview.md").write_text("# Final Overview\n", encoding="utf-8")
    (spec_dir / "requirements-overview.md").write_text(
        "# Requirements Overview\n", encoding="utf-8"
    )
    (spec_dir / "spec.md").write_text("# Spec\n", encoding="utf-8")
    (spec_dir / "plan.md").write_text("# Plan\n", encoding="utf-8")
    (spec_dir / "tasks.md").write_text("# Tasks\n", encoding="utf-8")
    (spec_dir / "plan-conformance.md").write_text(
        "# Plan Conformance\n", encoding="utf-8"
    )
    (spec_dir / "plan-conformance.json").write_text("{}\n", encoding="utf-8")
    (spec_dir / "requirements.lexicon.md").write_text(
        "ARTIFACT: SPEC\nTITLE: Requirements\n", encoding="utf-8"
    )

    text = render_artifact_index(spec_dir, generated_at=GENERATED_AT)

    assert "# Artifact Map" in text
    assert "This file is generated by Echelon." in text
    assert "Lifecycle stage: phase_a" in text
    assert "`tasks.md`" in text
    assert "`plan.md`" in text
    assert "| `spec.md` | Present |" in text
    assert "| `00-overview.md` | Present | Final overview |" in text
    assert "| `requirements-overview.md` | Present | Requirements orientation |" in text
    assert "| `plan-conformance.md` | Present | Plan conformance report |" in text
    assert "| `plan-conformance.json` | Present | Plan conformance data |" in text
    assert "Final PM/developer brief generated after planning conformance passes." in text
    assert "Phase 1 orientation generated with the requirements contract." in text
    assert "| `requirements.lexicon.md` | Present | Derived requirements index |" in text
    assert "Compiled from `spec.md` for deterministic Lexicon validation." in text
    assert "`requirements.lexicon.md`" not in text.partition("## Unclassified Files")[2]
    assert "Generated at: 2026-06-04T12:00:00+00:00" in text


@pytest.mark.unit
def test_phase_a_stage_reports_missing_required_files(tmp_path: Path) -> None:
    spec_dir = _make_spec_dir(tmp_path)

    text = render_artifact_index(spec_dir, generated_at=GENERATED_AT)

    assert "Lifecycle stage: phase_a" in text
    assert "| `spec.md` | Missing |" in text
    assert "| `00-overview.md` | Missing |" in text
    assert "| `requirements-overview.md` | Missing |" in text
    assert "| `plan-conformance.md` | Missing |" in text
    assert "| `plan-conformance.json` | Missing |" in text
    assert "| `plan.md` | Missing |" in text
    assert "| `tasks.md` | Missing |" in text
    assert "`00-overview.md` - Final overview" in text
    assert "`plan-conformance.md` - Plan conformance report" in text
    assert "`spec.md` - Feature contract" in text
    assert "`plan.md` - Implementation plan" in text
    assert "`tasks.md` - Task ledger" in text


@pytest.mark.unit
def test_optional_missing_files_do_not_appear_as_required_gaps(tmp_path: Path) -> None:
    spec_dir = _make_spec_dir(tmp_path)

    text = render_artifact_index(spec_dir, generated_at=GENERATED_AT)

    assert "| `spec-diagram.png` | Optional missing |" in text
    assert "`spec-diagram.png` - Spec diagram PNG" not in text


@pytest.mark.unit
def test_unclassified_top_level_files_are_listed(tmp_path: Path) -> None:
    spec_dir = _make_spec_dir(tmp_path)
    (spec_dir / "surprise-notes.md").write_text("# Notes\n", encoding="utf-8")
    (spec_dir / "tasks.md").write_text("# Tasks\n", encoding="utf-8")

    text = render_artifact_index(spec_dir, generated_at=GENERATED_AT)

    assert "## Unclassified Files" in text
    assert "`surprise-notes.md`" in text
    assert "`tasks.md`" in text
    assert "- `tasks.md`" not in text


@pytest.mark.unit
def test_verified_stage_detected_from_verification_summary(tmp_path: Path) -> None:
    spec_dir = _make_spec_dir(tmp_path)
    (spec_dir / "verification-summary.md").write_text("# Verified\n", encoding="utf-8")

    assert infer_lifecycle_stage(spec_dir) == "verified"

    text = render_artifact_index(spec_dir, generated_at=GENERATED_AT)
    assert "Lifecycle stage: verified" in text
    assert "| `gap-report.md` | Missing |" in text
    assert "| `verification-summary.md` | Present |" in text


@pytest.mark.unit
def test_landed_stage_detected_from_frontmatter_status(tmp_path: Path) -> None:
    spec_dir = _make_spec_dir(tmp_path)
    (spec_dir / "spec.md").write_text(
        "---\nstatus: landed\n---\n# Spec\n",
        encoding="utf-8",
    )
    (spec_dir / "verification-summary.md").write_text("# Verified\n", encoding="utf-8")

    assert infer_lifecycle_stage(spec_dir) == "landed"

    text = render_artifact_index(spec_dir, generated_at=GENERATED_AT)
    assert "Lifecycle stage: landed" in text


@pytest.mark.unit
def test_ready_to_land_stage_detected_as_verified(tmp_path: Path) -> None:
    spec_dir = _make_spec_dir(tmp_path)
    (spec_dir / "spec.md").write_text(
        "---\nstatus: ready_to_land\n---\n# Spec\n",
        encoding="utf-8",
    )

    assert infer_lifecycle_stage(spec_dir) == "verified"


@pytest.mark.unit
def test_write_artifact_index_overwrites_only_artifacts_md(tmp_path: Path) -> None:
    spec_dir = _make_spec_dir(tmp_path)
    spec_path = spec_dir / "spec.md"
    other_path = spec_dir / "notes.md"
    artifacts_path = spec_dir / "ARTIFACTS.md"
    spec_path.write_text("# Spec\n", encoding="utf-8")
    other_path.write_text("leave me alone\n", encoding="utf-8")
    artifacts_path.write_text("old map\n", encoding="utf-8")

    result = write_artifact_index(spec_dir, generated_at=GENERATED_AT)

    assert result == artifacts_path
    assert artifacts_path.read_text(encoding="utf-8") != "old map\n"
    assert "Generated at: 2026-06-04T12:00:00+00:00" in artifacts_path.read_text(
        encoding="utf-8"
    )
    assert spec_path.read_text(encoding="utf-8") == "# Spec\n"
    assert other_path.read_text(encoding="utf-8") == "leave me alone\n"
